version: '3.8'

services:
  node_backend:
    container_name: node_backend
    image: node:14
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=aworld
      - PGHOST=db
    depends_on:
      - db
  
  db:
    container_name: db
    image: 'postgres:13.2'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aworld
    volumes:
      - pgdata1:/var/lib/postgresql/data
      
volumes:
  pgdata1: {}
