version: '3.8'

services:
  node_backend:
    container_name: node_backend
    image: node:14
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=aworld
      - PGHOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"